import { api } from '../utils/api';
import { useState, useEffect } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function ReorderAnalysis({ theme, user }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedItem, setSelectedItem] = useState(null);
  const [orderSuccess, setOrderSuccess] = useState(null);
  const [filter, setFilter] = useState("All");
  const [placingOrder, setPlacingOrder] = useState(false);
  const [notes, setNotes] = useState("");

useEffect(() => {
  api.get('/api/reorder-analysis')
    .then(r => r?.json())
    .then(d => { if(d) { setData(d); setLoading(false); } });
}, []);
  const generatePO_PDF = (item, poNumber, expectedDelivery) => {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString('en-IN');

    // Header
    doc.setFillColor(26, 26, 46);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("PURCHASE ORDER", 105, 18, { align: "center" });
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`PO Number: ${poNumber}`, 105, 30, { align: "center" });

    // Company Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Roquette India Pvt. Ltd.", 14, 55);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("Rudrapur Plant, Uttarakhand", 14, 62);
    doc.text(`Date: ${today}`, 14, 69);
    doc.text(`Expected Delivery: ${expectedDelivery}`, 14, 76);

    // Supplier Info
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Supplier Details:", 120, 55);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(item.Supplier, 120, 62);
    doc.text(`Plant: ${item.Plant}`, 120, 69);

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 82, 196, 82);

    // Order Details Table
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Order Details", 14, 92);

    autoTable(doc, {
      startY: 97,
      head: [["Field", "Details"]],
      body: [
        ["Material ID", item.Material_ID],
        ["Description", item.Description],
        ["Category", item.Category],
        ["Order Quantity", `${item.EOQ} ${item.Unit}`],
        ["Unit Price", `₹${item.Unit_Price_INR.toLocaleString('en-IN')}`],
        ["Total Amount", `₹${item.Total_Order_Cost.toLocaleString('en-IN')}`],
        ["Current Stock", `${item.Current_Stock} ${item.Unit}`],
        ["Minimum Level", `${item.Min_Stock_Level} ${item.Unit}`],
        ["Days Until Stockout", `${item.Days_Until_Stockout} days`],
        ["Lead Time", `${item.Lead_Time_Days} days`],
        ["Urgency", item.Urgency],
      ],
      theme: "grid",
      headStyles: { fillColor: [26, 26, 46], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 248, 255] },
      margin: { left: 14, right: 14 }
    });

    // EOQ Explanation
    const afterTable = doc.lastAutoTable.finalY + 10;
    doc.setFillColor(240, 248, 255);
    doc.roundedRect(14, afterTable, 182, 28, 3, 3, 'F');
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(67, 97, 238);
    doc.text("📊 EOQ Calculation (Economic Order Quantity)", 20, afterTable + 9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(
      `EOQ = √(2 × Annual Demand × Ordering Cost / Holding Cost) = ${item.EOQ} ${item.Unit}`,
      20, afterTable + 18
    );

    // Notes
    if (notes) {
      const notesY = afterTable + 40;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text("Notes:", 14, notesY);
      doc.setFont("helvetica", "normal");
      doc.text(notes, 14, notesY + 7);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      "Generated by Roquette SAP Inventory System | Authorized Document",
      105, 285, { align: "center" }
    );

    doc.save(`PO_${poNumber}_${item.Description.replace(/ /g, '_')}.pdf`);
  };

  const placeOrder = async (item) => {
  setPlacingOrder(true);
  try {
    const res = await api.post('/api/purchase-orders', {
      material_id: item.Material_ID,
      description: item.Description,
      supplier: item.Supplier,
      plant: item.Plant,
      quantity: item.EOQ,
      unit: item.Unit,
      unit_price: item.Unit_Price_INR,
      notes: notes
    });
    const result = await res?.json();
    if (result?.success) {
      generatePO_PDF(item, result.po_number, result.expected_delivery);
      setOrderSuccess(result);
      setSelectedItem(null);
      setNotes("");
    }
  } catch (err) {
    alert("Error: " + err.message);
  }
  setPlacingOrder(false);
};

  if (loading) return (
    <div style={{ background: theme.cardBg, borderRadius: "12px", padding: "40px", textAlign: "center", color: theme.text }}>
      🔄 Reorder analysis ho rahi hai...
    </div>
  );

  const filteredItems = filter === "All"
    ? data.items
    : filter === "Reorder"
    ? data.items.filter(i => i.Needs_Reorder)
    : data.items.filter(i => i.Urgency === filter);

  return (
    <div>
      {/* Success Toast */}
      {orderSuccess && (
        <div style={{
          position: "fixed", top: "20px", right: "20px",
          background: "#2a9d8f", color: "white",
          padding: "16px 24px", borderRadius: "12px",
          boxShadow: "0 8px 24px rgba(0,0,0,0.2)",
          zIndex: 3000, animation: "slideIn 0.3s ease"
        }}>
          <div style={{ fontWeight: "600" }}>
            ✅ Purchase Order Created!
          </div>
          <div style={{ fontSize: "0.85rem", opacity: 0.9, marginTop: "4px" }}>
            {orderSuccess.po_number} | Delivery: {orderSuccess.expected_delivery}
          </div>
          <button
            onClick={() => setOrderSuccess(null)}
            style={{
              position: "absolute", top: "8px", right: "12px",
              background: "none", border: "none",
              color: "white", cursor: "pointer", fontSize: "1rem"
            }}
          >✕</button>
        </div>
      )}

      {/* Summary Cards */}
      <div style={{ display: "flex", gap: "16px", marginBottom: "24px", flexWrap: "wrap" }}>
        {[
          { label: "Needs Reorder", value: data.needs_reorder, bg: "#e63946", icon: "📋" },
          { label: "Critical", value: data.critical_count, bg: "#c0392b", icon: "🔴" },
          { label: "High Priority", value: data.high_count, bg: "#f4a261", icon: "🟡" },
          { label: "Total Budget Needed", value: `₹${(data.total_order_budget).toLocaleString('en-IN')}`, bg: "#4361ee", icon: "💰" },
        ].map((card, i) => (
          <div key={i} style={{
            background: card.bg, color: "white",
            borderRadius: "12px", padding: "20px 24px",
            flex: "1", minWidth: "180px",
            boxShadow: "0 4px 15px rgba(0,0,0,0.15)"
          }}>
            <div style={{ fontSize: "1.8rem" }}>{card.icon}</div>
            <div style={{ fontSize: "1.6rem", fontWeight: "bold", margin: "6px 0" }}>
              {card.value}
            </div>
            <div style={{ opacity: 0.85, fontSize: "0.85rem" }}>{card.label}</div>
          </div>
        ))}
      </div>

      {/* Main Table */}
      <div style={{
        background: theme.cardBg, borderRadius: "12px",
        padding: "24px", boxShadow: "0 2px 10px rgba(0,0,0,0.08)"
      }}>
        <div style={{
          display: "flex", justifyContent: "space-between",
          alignItems: "center", marginBottom: "16px", flexWrap: "wrap", gap: "12px"
        }}>
          <h3 style={{ margin: 0, color: theme.text }}>
            📋 Reorder Analysis — {filteredItems.length} Items
          </h3>
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
            {["All", "Reorder", "🔴 Critical", "🟡 High"].map(f => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                style={{
                  padding: "6px 14px", borderRadius: "20px",
                  border: "none", cursor: "pointer",
                  background: filter === f ? "#4361ee" : theme.bg,
                  color: filter === f ? "white" : theme.text,
                  fontWeight: filter === f ? "600" : "normal",
                  fontSize: "0.85rem"
                }}
              >
                {f}
              </button>
            ))}
          </div>
        </div>

        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.88rem" }}>
            <thead>
              <tr style={{ background: theme.bg }}>
                {["Material", "Supplier", "Stock", "Reorder Point", "EOQ", "Days Left", "Budget", "Urgency", "Action"].map(h => (
                  <th key={h} style={{
                    padding: "10px 12px", textAlign: "left",
                    borderBottom: `2px solid ${theme.border}`,
                    color: theme.text, whiteSpace: "nowrap"
                  }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filteredItems.map((item, i) => (
                <tr key={i} style={{
                  borderBottom: `1px solid ${theme.border}`,
                  background: item.Urgency === "🔴 Critical"
                    ? (theme.cardBg === "white" ? "#fff5f5" : "#2a1515")
                    : theme.cardBg
                }}>
                  <td style={{ padding: "10px 12px" }}>
                    <div style={{ fontWeight: "600", color: theme.text }}>
                      {item.Description.substring(0, 20)}
                    </div>
                    <div style={{ fontSize: "0.78rem", color: theme.subText }}>
                      {item.Material_ID} | {item.Plant}
                    </div>
                  </td>
                  <td style={{ padding: "10px 12px", color: theme.text }}>
                    {item.Supplier}
                  </td>
                  <td style={{ padding: "10px 12px" }}>
                    <span style={{
                      color: item.Needs_Reorder ? "#e63946" : "#2a9d8f",
                      fontWeight: "bold"
                    }}>
                      {item.Current_Stock}
                    </span>
                    <span style={{ color: theme.subText, fontSize: "0.8rem" }}>
                      /{item.Min_Stock_Level}
                    </span>
                  </td>
                  <td style={{ padding: "10px 12px", color: theme.text }}>
                    {item.Reorder_Point}
                  </td>
                  <td style={{ padding: "10px 12px", color: "#4361ee", fontWeight: "600" }}>
                    {item.EOQ} {item.Unit}
                  </td>
                  <td style={{ padding: "10px 12px" }}>
                    <span style={{
                      color: item.Days_Until_Stockout <= 7 ? "#e63946"
                        : item.Days_Until_Stockout <= 14 ? "#f4a261" : "#2a9d8f",
                      fontWeight: "600"
                    }}>
                      {item.Days_Until_Stockout === 999 ? "∞" : `${item.Days_Until_Stockout}d`}
                    </span>
                  </td>
                  <td style={{ padding: "10px 12px", color: theme.text }}>
                    ₹{item.Total_Order_Cost.toLocaleString('en-IN')}
                  </td>
                  <td style={{ padding: "10px 12px" }}>
                    <span style={{ fontSize: "0.85rem" }}>{item.Urgency}</span>
                  </td>
                  <td style={{ padding: "10px 12px" }}>
                    {item.Needs_Reorder && user.role !== "Viewer" && (
                      <button
                        onClick={() => setSelectedItem(item)}
                        style={{
                          background: "#4361ee", color: "white",
                          border: "none", padding: "6px 12px",
                          borderRadius: "6px", cursor: "pointer",
                          fontSize: "0.8rem", fontWeight: "600",
                          whiteSpace: "nowrap"
                        }}
                      >
                        📋 Place Order
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Order Modal */}
      {selectedItem && (
        <div
          onClick={() => setSelectedItem(null)}
          style={{
            position: "fixed", top: 0, left: 0,
            width: "100vw", height: "100vh",
            background: "rgba(0,0,0,0.5)",
            zIndex: 2000, display: "flex",
            alignItems: "center", justifyContent: "center"
          }}
        >
          <div
            onClick={e => e.stopPropagation()}
            style={{
              background: theme.cardBg, borderRadius: "16px",
              padding: "32px", width: "100%", maxWidth: "500px",
              boxShadow: "0 20px 60px rgba(0,0,0,0.3)", margin: "16px"
            }}
          >
            <h2 style={{ margin: "0 0 4px", color: theme.text }}>
              📋 Place Purchase Order
            </h2>
            <p style={{ margin: "0 0 24px", color: theme.subText, fontSize: "0.85rem" }}>
              {selectedItem.Description} | {selectedItem.Material_ID}
            </p>

            {/* Order Summary */}
            <div style={{
              background: theme.bg, borderRadius: "10px",
              padding: "16px", marginBottom: "16px"
            }}>
              {[
                ["Supplier", selectedItem.Supplier],
                ["Plant", selectedItem.Plant],
                ["Order Quantity (EOQ)", `${selectedItem.EOQ} ${selectedItem.Unit}`],
                ["Unit Price", `₹${selectedItem.Unit_Price_INR.toLocaleString('en-IN')}`],
                ["Total Cost", `₹${selectedItem.Total_Order_Cost.toLocaleString('en-IN')}`],
                ["Expected Delivery", `${selectedItem.Lead_Time_Days} days`],
                ["Urgency", selectedItem.Urgency],
              ].map(([label, value], i) => (
                <div key={i} style={{
                  display: "flex", justifyContent: "space-between",
                  padding: "6px 0",
                  borderBottom: i < 6 ? `1px solid ${theme.border}` : "none"
                }}>
                  <span style={{ color: theme.subText, fontSize: "0.88rem" }}>{label}</span>
                  <span style={{ color: theme.text, fontWeight: "600", fontSize: "0.88rem" }}>{value}</span>
                </div>
              ))}
            </div>

            {/* Notes */}
            <textarea
              placeholder="Additional notes (optional)..."
              value={notes}
              onChange={e => setNotes(e.target.value)}
              style={{
                width: "100%", padding: "10px 14px",
                borderRadius: "8px", border: `1px solid ${theme.border}`,
                background: theme.inputBg, color: theme.text,
                fontSize: "0.9rem", resize: "vertical",
                minHeight: "80px", boxSizing: "border-box",
                marginBottom: "16px"
              }}
            />

            {/* Buttons */}
            <div style={{ display: "flex", gap: "10px" }}>
              <button
                onClick={() => setSelectedItem(null)}
                style={{
                  flex: 1, padding: "12px",
                  background: theme.bg, color: theme.text,
                  border: `1px solid ${theme.border}`,
                  borderRadius: "8px", cursor: "pointer", fontWeight: "600"
                }}
              >
                Cancel
              </button>
              <button
                onClick={() => placeOrder(selectedItem)}
                disabled={placingOrder}
                style={{
                  flex: 2, padding: "12px",
                  background: placingOrder ? "#ccc" : "#4361ee",
                  color: "white", border: "none",
                  borderRadius: "8px", cursor: placingOrder ? "not-allowed" : "pointer",
                  fontWeight: "600"
                }}
              >
                {placingOrder ? "Creating..." : "✅ Confirm & Generate PO"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default ReorderAnalysis;